name: ArcaneMoney
version: 1.0
main: com.thiagocgo.arcanemoney.ArcaneMoney
api-version: 1.13
commands:
  money:
    description: Comandos administrativos do ArcaneMoney
    usage: /<command> [vip|adicionar|remover|saldo|transferir|reload]
    permission: arcanemoney.admin
  saldo:
    description: Verifica o saldo do jogador
    usage: /<command> [player]
  transferir:
    description: Transfere dinheiro para outro jogador
    usage: /<command> <player> <amount>
  sell:
    description: Vende itens para o servidor
    usage: /<command>
  trade:
    description: Abre a interface de troca
    usage: /<command>
  criarloja:
    description: Cria uma loja
    usage: /<command>
  listlojas:
    description: Lista todas as lojas
    usage: /<command>
permissions:
  arcanemoney.admin:
    description: Permite acesso aos comandos administrativos
    default: op
  arcanemoney.vip:
    description: Permite acesso a benefícios VIP (desconto, yield)
    default: false
  arcanemoney.staff:
    description: Permite acesso a benefícios de staff (yield)
    default: false